# 标准: 符合插件命名规范 xx_plugin.
name: mobpush_plugin

# 标准: 必须添加产品说明信息,需要修改时变更.
description: 这是一个基于 MobPush 功能的扩展的 Flutter 插件。使用此插件能够帮助您在使用 Flutter 开发应用时，快速地实现推送功能。

# 标准: 每次发布新版本，都需要更新版本号.
version: 1.2.4

# 标准: 添加官网对应插件项目的首页.
homepage: http://www.mob.com/mobService/mobpush

environment:
# 标准: 最低版本 2.1.0 , 最高版本 x.x.x
  sdk: ">=2.12.0 <3.0.0"

# 标准: 最低版本 1.12.0.
  flutter: ">=1.12.0"

dependencies:
  # 标准: 依赖插件，只能是官方的，对于第三方的，需要自己实现，避免冲突
  flutter:
    sdk: flutter
  #json_annotation: ^4.0.1. 第三方，不能用

dev_dependencies:
  # 标准: 依赖插件，只能是官方的，对于第三方的，需要自己实现，避免冲突
  flutter_test:
    sdk: flutter
  #json_annotation: ^4.0.1. 第三方，不能用

flutter:

  # 标准: 现在需要区分安卓/iOS的包,否则会报错.pluginClass保持统一.
  plugin:
    platforms:
      android:
        package: com.mob.flutter.mobpush
        pluginClass: MobpushPlugin
      ios:
        pluginClass: MobpushPlugin

# 标准: 需要检查部分项目的明文配置信息(通过try命令可以检查是否报错)，push的google-services,  share的MobSDK.gradle
false_secrets:
  - example/android/app/google-services.json
